name: valgrind
version: '3.19.0.RC2'
summary: A programming tool for memory debugging, leak detection, and profiling.
description: |
  Valgrind is an instrumentation framework for building dynamic analysis tools.
  There are Valgrind tools that can automatically detect many memory management
  and threading bugs, and profile your programs in detail. You can also use
  Valgrind to build new tools.

  The Valgrind distribution currently includes seven production-quality tools:
  a memory error detector, two thread error detectors, a cache and
  branch-prediction profiler, a call-graph generating cache and
  branch-prediction profiler, and two different heap profilers. It also includes
  an experimental SimPoint basic block vector generator.

  **Extra Tool**

  This snap also includes the experimental tool Failgrind, which is not part of
  the upstream Valgrind project.

  **Documentation**

  Documentation for this release which includes the Failgrind tool is available
  at http://valgrind.ral.me/

  The official Valgrind documentation is available at
  http://valgrind.org/docs/manual/index.html

  **Snap Package**

  The source for this snap package can be found
  https://github.com/ralight/valgrind-snap

  **Disclaimer**

  This package is not currently affiliated with the upstream valgrind project.

base: core18
grade: stable
confinement: classic
#contact: roger@atchoo.org
#donation: https://github.com/sponsors/ralight
#issues: https://github.com/ralight/valgrind-snap/issues
license: GPL-2.0+
#source-code: https://github.com/ralight/valgrind-snap
compression: lzo

apps:
  callgrind-annotate:
    command: usr/bin/callgrind_annotate

  callgrind-control:
    command: usr/bin/callgrind_control

  cg-annotate:
    command: usr/bin/cg_annotate

  cg-diff:
    command: usr/bin/cg_diff

  cg-merge:
    command: usr/bin/cg_merge

  ms-print:
    command: usr/bin/ms_print

  valgrind:
    command: usr/bin/valgrind
    environment:
      VALGRIND_LIB: $SNAP/usr/libexec/valgrind

  valgrind-di-server:
    command: usr/bin/valgrind-di-server

  valgrind-listener:
    command: usr/bin/valgrind-listener

  vgdb:
    command: usr/bin/vgdb

parts:
  patches:
    source: patches/
    plugin: dump
    organize:
      0001-Failgrind.patch: patches/0001-Failgrind.patch
    prime: [-*]

  valgrind:
    after: [patches]
    plugin: autotools
    source: https://sourceware.org/pub/valgrind/valgrind-$SNAPCRAFT_PROJECT_VERSION.tar.bz2
    override-pull: |
      snapcraftctl pull
      patch -p1 < $SNAPCRAFT_STAGE/patches/0001-Failgrind.patch
    override-build: |
      ./autogen.sh
      snapcraftctl build
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --enable-lto
    prime: [-usr/share/doc/valgrind/valgrind_manual.ps]
